### ISSUE TITLE
Bad request response for lists and sets as query parameters

### ISSUE THREAD

**Issue by thehgregor** [palantir/conjure-go#128]
## What happened?

A list or set `somefield` as URL parameter is translated into a URL string  `somefield=%5Bvalue1,value2%5D`. This format is not supported by all servers, and in our specific case we get an HTTP 400 response.

Example for such a field:
```
{
    "fieldName": "somefield",
    "type": {
        "type": "optional",
        "optional": {
            "itemType": {
                "type": "set",
                "set": {
                    "itemType": {
                        "type": "external",
                        "external": {
                            "externalReference": {
                                "name": "Somefield",
                                "package": "com.somepackage"
                            },
                            "fallback": {
                                "type": "primitive",
                                "primitive": "STRING"
                            }
                        }
                    }
                }
            }
        }
    },
    "docs": null
}
```

## What did you want to happen?

It seems that a translation like `somefield=value1&somefield=value2` would be supported more widely (in our case this is the only format that our server accepts). This seems not to be supported by URL translation via Encode in the net/url package (as used in github.com/palantir/conjure-go-runtime/v2@v2.2.0/conjure-go-client/httpclient/client.go) though.

**Comment by bmoylan** [comment]
Yep, this is a bug! The [wire spec](https://github.com/palantir/conjure/blob/master/docs/spec/wire.md#22-query-parameters) says:
> For query parameters of type list<T> or set<T>, each value should result in one key=value pair, separated by &. Note that the order of values must be preserved for list<T>, but is semantically unimportant for set<T>. E.g.: `/recipes?category=foo&category=bar&category=baz`

I've opened #130 which should fix this.
