### ISSUE TITLE
Conjure errors should have comparison helper function

### ISSUE THREAD

**Issue by asanderson15** [palantir/conjure-go#141]
## What happened?

A common use case is to look at a returned error and determine whether it's a known type and handle accordingly. E.g.:

```
err := doSomething()
if err != nil {
    if e, ok := werror.RootCause(err).(errors.Error); ok {
        if e.Name() == "Namespace:FooBarConjureError" {
            // do something
        }
    }
}
```

That's not great because (a) it's a lot of boilerplate and (b) it requires copy-pasting the error name from the generated conjure since it's not exported as a const.

## What did you want to happen?

Instead, we should generate a small helper function:

```
func IsFooBarConjureError(err error) bool {
    if err == nil {
        return false
    }
    if e, ok := werror.RootCause(err).(errors.Error); ok {
        if e.Name() == "Namespace:FooBarConjureError" {
           return true
        }
    }
    return false
}
```

This would turn the above code into:

```
err := doSomething()
if err != nil && api.IsFooBarConjureError(err) {
    // do something
}
```

**Comment by bmoylan** [comment]
Overall in sync with this. Two thoughts on the proposed helper implementation:
- We can return false if err == nil so the caller doesn't have to
- Would it be better to check against the concrete type instead of the name? E.g. 

```go
func IsFooBarConjureError(err error) bool {
    if err == nil {
        return false
    }
    _, ok := werror.RootCause(err).(*FooBarConjureError)
    return ok
}
```

**Comment by asanderson15** [comment]
Yeah, just added the nil handling to the above example. But yeah, your code is better.

**Comment by asanderson15** [comment]
In practice, the caller will still usually need to check for nil because usually you still have to handle a non-nil error even if it's not the type you're looking for.

**Comment by tabboud** [comment]
This seems reasonable to me, and is a nice abstraction over the type casting.
When there are multiple possible errors the usage becomes a little different since the helpers return `bool`s we would have to do something like this:
```go
err := doSomething()
if err != nil {
	switch {
	case IsFooConjureError(err):
		// ...
	case IsBarConjureError(err):
		// ...
	default:
		// ...
	}
}
```

We don't save much from the regular code path for multiple errors, but I bet this is less frequently used to begin with.
```go
err := doSomething()
if err != nil {
	switch werror.RootCause(err).(type) {
	case *FooConjureError:
		// ...
	case *BarConjureError:
		// ...
	default:
		// ...
	}
}
```

**Comment by bmoylan** [comment]
The other nice thing about doing the type switch instead of boolean conditions is you can store the cast value

```go
err := doSomething()
if err != nil {
    switch e := werror.RootCause(err).(type) {
    case *FooConjureError:
        handleFooParam(e.Foo)
        // ...
    case *BarConjureError:
        handleBarParam(e.Bar)
        // ...
    default:
        // ...
    }
}
```

Ultimately I think it depends on what you're doing, and while the boolean helper functions are appropriate in some cases I think some of the existing patterns would stick around.
