### ISSUE TITLE
Generated code does not pass linting

### ISSUE THREAD

**Issue by lycarter** [palantir/conjure-go#164]
## What happened?
golint enforces [initialisms](https://github.com/golang/go/wiki/CodeReviewComments#initialisms), while conjure does not. That results in generated code which does not comply with golint.

Generated code
```
GetServiceBackupDirectoryV2(req.Context(), backupId, nodeId, serviceId, mount)
```
Here `backupId` should be `backupID`, `nodeId` should be `nodeID`, and `serviceId` should be `serviceID`

## What did you want to happen?

Generated go code should comply to go's style guidelines by adjusting capitalization as required.

**Comment by nmiyake** [comment]
This will likely be a "Won't fix". The generated code will certainly be gofmt-compatible, but satisfying all golint warnings is a higher bar -- especially for things like variable names, it adds a lot of complexity in terms of maintaining mappings but ensuring that there are no collisions after transforms etc. The issue of golint and generated code is a more general one, and I don't think this stance is crazy -- see for example https://github.com/golang/lint/issues/176#issuecomment-442601599.

If you're using godel as a build tool, then typically the pattern we use is to generate Conjure output into a specific directory and use godel settings to ignore checks on that directory.

**Comment by nmiyake** [comment]
Closing the issue since I don't think we will fix it, but happy to trouble-shoot your particular situation or to listen to further input.
