### ISSUE TITLE
Iterable Binary return type inconsistent with other binary types

### ISSUE THREAD

**Issue by AdamDeHovitz** [palantir/conjure-go#194]
Unlike with other return types, conjure-go special cases `binary` endpoints to use the `ReadCloser` stream type rather than the default `[]byte`. Specifically, endpoints that return `binary` use `ReadCloser` while `optional<binary>` endpoints will return `*ReadCloser` after the resolution of https://github.com/palantir/conjure-go/issues/192. In contrast endpoints with either a `set<binary>` or `list<binary>` type use an unstreamable `[][]byte` go type. Ultimately this might be the right choice but we should compare the implementation against `conjure-java`, validate that this type works, and add unit/integration testing to guarantee this behavior.

**Comment by AdamDeHovitz** [comment]
I did some testing in java and found the following type conversions from conjure to java:
`binary` -> `BinaryResponseBody`
`optional<binary>` -> `Optional<BinaryResponseBody>`
`list<binary>` -> `List<ByteBuffer`

**Comment by gregakinman** [comment]
@AdamDeHovitz `List<ByteBuffer>` doesn't look like streaming to me, so at first glance it looks like this is consistent with the Java implementation, but I'm not 100% sure

**Comment by bmoylan** [comment]
This is working as intended: `list<binary>` is a JSON Array of base64-encoded strings, while `binary` and `optional<binary>` are opaque octet-stream bodies.
