### ISSUE TITLE
Use generics to improve Ergonomics of generated union types

### ISSUE THREAD

**Issue by jamesross3** [palantir/conjure-go#298]
### Problem
Today, Conjure-generated union types in Go are harder to handle than their counterparts, primarily due to the lack of generics. If I want to return a value with type `T` determined by visiting a union type, I currently have to either (1) define a stateful struct which implements the existing `Visitor` or `VisitorWithContext` interface, or (2) leverage closures by instantiating a variable outside of the AcceptFuncs method and setting it in the Visit methods provided to AcceptFuncs. These both have disadvantages; the former approach makes reuse of the stateful struct a recipe for concurrency bugs, and the latter forces the use of closures, which can degrade readability.

### Proposed Solution
The advent of generics in go1.18 lets us generate type-parametrized code to make usage much cleaner. Given the following union type definition:
```
MyUnion:
  union:
    stringVal: string
    boolVal: bool
```
I propose generating this code:
```
type MyUnionWithT[T any] MyUnion

func (u myUnionWithT) Accept(ctx context.Context, v myUnionVisitorWithT[T]) (T, error) {
  switch u.typ {
    case default:
      if u.typ == "" { return nil, fmt.Errorf("unknown")}
      return v.VisitUnknown(ctx, u.typ)
    case "stringVal":
      return v.VisitStringVal(ctx, *u.stringVal)
    case "boolVal":
      return v.VisitBoolVal(ctx, *u.boolVal)
  }
}

type MyUnionVisitorWithT[T any] interface {
	VisitStringVal(ctx context.Context, v string) (T, error)
	VisitBoolVal(ctx context.Context, v bool) (T, error)
	VisitUnknown(ctx context.Context, typ string) (T, error)
}
```

Where example usage looks like:
```
func Stringify(ctx, context.Context, myUnion MyUnion) (string, error) {
  var stringifyingVisitor MyUnionVisitorWithT[string] = NewStringifyingVisitor()
  return MyUnionWithT[string](myUnion).Accept(ctx, stringifyingVisitor)
}
```

**Comment by jamesross3** [comment]
Draft: https://github.com/palantir/conjure-go/pull/300

**Comment by tabboud** [comment]
Completed as of https://github.com/palantir/conjure-go/pull/300
