### ISSUE TITLE
Do not panic when processing Conjure with an external type

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-go#33]
When processing a valid Conjure definition that contains:

```
              "type" : "external",
              "external" : {
                "externalReference" : {
                  "name" : "ExampleExternalType",
                  "package" : "com.palantir.types"
                },
                "fallback" : {
                  "type" : "primitive",
                  "primitive" : "STRING"
                }
```

`conjure-go` panics with the following output:

```
panic: runtime error: index out of range

goroutine 1 [running]:
.../vendor/github.com/palantir/conjure-go/conjure/types.NewGoTypeFromExternalType(0xc0005d6140, 0x13, 0xc0005d6180, 0x19, 0xc0005347f0, 0x9, 0xc00057a9a0, 0x0, 0x0, 0x0, ...)
        .../vendor/github.com/palantir/conjure-go/conjure/types/types.go:226 +0x158
```

Because external types are on a path towards deprecation I don't think we need to add support for specifying external Go types, but at the very least we should try to parse and use the fallback type (and use the `any` type if a fallback doesn't exist).

If that's too much work, then a stopgap could be to just use the `any` type for now -- even that would be strictly better (while technically still fulfilling the spec) than panicking on a valid definition as we do now.

**Comment by bwaldrep** [comment]
Fixed by #40
