### ISSUE TITLE
Provide convenience function for using binary arguments

### ISSUE THREAD

**Issue by johnhferland** [palantir/conjure-go#51]
We have been writing repetitive code for sending protobuf across the wire:
```
func() io.ReadCloser { return ioutil.NopCloser(bytes.NewReader(body)) 
```

API recommended by @bmoylan:
```
BodyProviderFromBytes(body []byte) func() io.ReadCloser
```

**Comment by bmoylan** [comment]
Addressed in https://github.com/palantir/conjure-go-runtime/pull/695 and https://github.com/palantir/conjure-go/pull/620
