### ISSUE TITLE
Improve API for sending binary

### ISSUE THREAD

**Issue by johnhferland** [palantir/conjure-go#52]
To send a slice of bytes across the wire we need to convert the bytes to a `func () io.ReadCloser`, which is pretty cumbersome. I would like to propose we expose an API where we can simply provide `[]byte` and conjure-go will do the rest.
Before:
```
c.PutEndpoint(ctx, func() io.ReadCloser { return ioutil.NopCloser(bytes.NewReader(bodyBytes)) })
```
After:
```
c.PutEndpoint(ctx, bodyBytes)
```

**Comment by bmoylan** [comment]
Addressed in https://github.com/palantir/conjure-go-runtime/pull/695 and https://github.com/palantir/conjure-go/pull/620
