### ISSUE TITLE
ResourceIdentifier aliases do not work as expected

### ISSUE THREAD

**Issue by chris05atm** [palantir/conjure-go#68]
## What happened?

An internal product defines a ResourceIdentifier type alias like so:

    // The RID for a Table.
    type TableRid rid.ResourceIdentifier

This `TableRid` type is used as a service query parameter:

    postEvent:
        http: POST /edits/tables/{tableRid}/events
        args:
            tableRid:
                docs: The identifier for the Table being edited.
                type: TableRid
                markers:
                    - Safe

which generates this interface function:

    PostEvent(ctx context.Context, authHeader bearertoken.Token, onBehalfOfArg *uuid.UUID, tableRidArg TableRid, tableEditedEventPostRequestArg TableEditedEventPostRequest) error

The client code generated uses `fmt.Sprint` on the `TableRid` object to path escape the parameter:

    requestParams = append(requestParams, httpclient.WithPathf("/storage/edits/tables/%s/events", url.PathEscape(fmt.Sprint(tableRidArg))))

`fmt.Sprint` does not call `TableRid.String()` because this does not exist on the alias. A generic string is used and the rid string ends up space delimited instead of what `ResourceIdentifier.String()` does.

Once the parameter is passed incorrectly the conjure-java based server returns errors because TableRid does not convert to a properly formatted rid string.

## What did you want to happen?

Aliased `ResourceIdentifier`s should carry forward the ResourceIdentifier.String() func.

**Comment by nmiyake** [comment]
Thanks, this is definitely a valid issue -- we should ensure that any type that aliases a type with a custom `String()` function redeclares its own `String()` function.
